import { Product } from "@/types";
import {
  Wrench,
  Laptop,
  Shirt,
  Home,
  BookOpen,
  HeartPulse,
  Dumbbell,
  Car,
  ShoppingBasket,
  ToyBrick,
  Camera,
  Smartphone,
  Glasses,
  Sofa,
  Leaf,
  SoapDispenserDroplet,
  Tent,
  Gamepad,
  ShipWheel,
  Milk,
  PillBottle,
  Watch,
  UtensilsCrossed,
  Keyboard,
  Briefcase,
  Paintbrush,
  Umbrella,
  BedDouble,
  LampDesk,
  Cpu,
} from "lucide-react";

export const products: Product[] = [
  {
    id: "1",
    name: "Screwdriver",
    supplier: "ToolSupplier Inc.",
    sku: "54614",
    category: "Electronics",
    status: "Draft",
    quantityInStock: 50,
    price: 14.99,
    icon: Wrench,
  },
  {
    id: "2",
    name: "Laptop Pro 15",
    supplier: "TechWare",
    sku: "LTP-9021",
    category: "Electronics",
    status: "Published",
    quantityInStock: 23,
    price: 1299.99,
    icon: Laptop,
  },
  {
    id: "3",
    name: "Casual T-Shirt",
    supplier: "FashionHub",
    sku: "TSH-001",
    category: "Fashion",
    status: "Published",
    quantityInStock: 200,
    price: 19.99,
    icon: Shirt,
  },
  {
    id: "4",
    name: "Garden Hose 50ft",
    supplier: "GreenLand Supplies",
    sku: "HOS-5050",
    category: "Home & Garden",
    status: "Inactive",
    quantityInStock: 40,
    price: 29.99,
    icon: Home,
  },
  {
    id: "5",
    name: "Self-Help Book",
    supplier: "BookStore Co.",
    sku: "BK-SELF-001",
    category: "Books",
    status: "Published",
    quantityInStock: 85,
    price: 12.99,
    icon: BookOpen,
  },
  {
    id: "6",
    name: "Vitamin C Serum",
    supplier: "BeautyLine",
    sku: "VITC-222",
    category: "Beauty & Personal Care",
    status: "Draft",
    quantityInStock: 150,
    price: 24.99,
    icon: HeartPulse,
  },
  {
    id: "7",
    name: "Adjustable Dumbbell",
    supplier: "FitGear",
    sku: "DB-ADJ-40",
    category: "Sports & Outdoors",
    status: "Published",
    quantityInStock: 35,
    price: 89.99,
    icon: Dumbbell,
  },
  {
    id: "8",
    name: "Toy Building Set",
    supplier: "PlayZone",
    sku: "TOY-LEG-900",
    category: "Toys & Games",
    status: "Published",
    quantityInStock: 120,
    price: 39.99,
    icon: ToyBrick,
  },
  {
    id: "9",
    name: "Car Air Freshener",
    supplier: "AutoCare Ltd.",
    sku: "CAR-FR-303",
    category: "Automotive",
    status: "Inactive",
    quantityInStock: 300,
    price: 5.99,
    icon: Car,
  },
  {
    id: "10",
    name: "Organic Almonds",
    supplier: "HealthyFoods",
    sku: "GR-ALMD-888",
    category: "Groceries",
    status: "Published",
    quantityInStock: 75,
    price: 14.5,
    icon: ShoppingBasket,
  },
  {
    id: "11",
    name: "DSLR Camera",
    supplier: "CamWorld",
    sku: "CAM-DSLR-101",
    category: "Electronics",
    status: "Published",
    quantityInStock: 18,
    price: 849.0,
    icon: Camera,
  },
  {
    id: "12",
    name: "Smartphone X1",
    supplier: "SmartTech",
    sku: "PHN-X1",
    category: "Electronics",
    status: "Draft",
    quantityInStock: 60,
    price: 999.99,
    icon: Smartphone,
  },
  {
    id: "13",
    name: "Reading Glasses",
    supplier: "OptiLook",
    sku: "GLS-READ-55",
    category: "Fashion",
    status: "Published",
    quantityInStock: 110,
    price: 49.99,
    icon: Glasses,
  },
  {
    id: "14",
    name: "Sofa 3-Seater",
    supplier: "HomeComfort",
    sku: "SOFA-3S-789",
    category: "Home & Garden",
    status: "Draft",
    quantityInStock: 10,
    price: 599.99,
    icon: Sofa,
  },
  {
    id: "15",
    name: "Organic Plant Food",
    supplier: "GreenThumb",
    sku: "PLNT-FD-222",
    category: "Home & Garden",
    status: "Published",
    quantityInStock: 95,
    price: 9.99,
    icon: Leaf,
  },
  {
    id: "16",
    name: "Natural SoapDispenserDroplet  Bar",
    supplier: "NatureCare",
    sku: "SoapDispenserDroplet -NAT-010",
    category: "Beauty & Personal Care",
    status: "Published",
    quantityInStock: 400,
    price: 3.49,
    icon: SoapDispenserDroplet,
  },
  {
    id: "17",
    name: "Camping Tent 4-Person",
    supplier: "AdventureGear",
    sku: "TENT-4P-321",
    category: "Sports & Outdoors",
    status: "Published",
    quantityInStock: 25,
    price: 139.99,
    icon: Tent,
  },
  {
    id: "18",
    name: "Wireless Game Controller",
    supplier: "PlayWorld",
    sku: "GAME-CON-102",
    category: "Toys & Games",
    status: "Published",
    quantityInStock: 65,
    price: 59.99,
    icon: Gamepad,
  },
  {
    id: "19",
    name: "Steering Wheel Cover",
    supplier: "AutoZone",
    sku: "STR-WHL-444",
    category: "Automotive",
    status: "Inactive",
    quantityInStock: 90,
    price: 11.99,
    icon: ShipWheel,
  },
  {
    id: "20",
    name: "Organic Milk 1L",
    supplier: "FarmFresh",
    sku: "MLK-1L-ORG",
    category: "Groceries",
    status: "Published",
    quantityInStock: 200,
    price: 2.99,
    icon: Milk,
  },
  {
    id: "21",
    name: "Omega-3 PillBottles",
    supplier: "WellnessLab",
    sku: "CAP-OMEGA3-60",
    category: "Health & Wellness",
    status: "Draft",
    quantityInStock: 180,
    price: 19.99,
    icon: PillBottle,
  },
  {
    id: "22",
    name: "Smartwatch Z3",
    supplier: "SmartGear",
    sku: "WTCH-Z3-999",
    category: "Electronics",
    status: "Published",
    quantityInStock: 45,
    price: 229.99,
    icon: Watch,
  },
  {
    id: "23",
    name: "Stainless Steel Cutlery Set",
    supplier: "KitchenWorld",
    sku: "CUT-SS-20PC",
    category: "Home & Garden",
    status: "Published",
    quantityInStock: 130,
    price: 34.99,
    icon: UtensilsCrossed,
  },
  {
    id: "24",
    name: "Wireless Keyboard",
    supplier: "TechBase",
    sku: "KEY-WLS-002",
    category: "Electronics",
    status: "Inactive",
    quantityInStock: 90,
    price: 49.99,
    icon: Keyboard,
  },
  {
    id: "25",
    name: "Leather Briefcase",
    supplier: "WorkStyle",
    sku: "BAG-BRF-777",
    category: "Fashion",
    status: "Published",
    quantityInStock: 28,
    price: 179.99,
    icon: Briefcase,
  },
  {
    id: "26",
    name: "Acrylic Paint Set",
    supplier: "ArtStation",
    sku: "ART-PAINT-003",
    category: "Others",
    status: "Draft",
    quantityInStock: 70,
    price: 22.99,
    icon: Paintbrush,
  },
  {
    id: "27",
    name: "Travel Umbrella",
    supplier: "RainyDays",
    sku: "UMBL-TVL-202",
    category: "Fashion",
    status: "Published",
    quantityInStock: 85,
    price: 9.49,
    icon: Umbrella,
  },
  {
    id: "28",
    name: "Queen Size Bed Frame",
    supplier: "SleepWell",
    sku: "BED-QS-890",
    category: "Home & Garden",
    status: "Published",
    quantityInStock: 12,
    price: 649.99,
    icon: BedDouble,
  },
  {
    id: "29",
    name: "Desk Lamp LED",
    supplier: "BrightLights",
    sku: "LMP-DSK-LED",
    category: "Home & Garden",
    status: "Draft",
    quantityInStock: 60,
    price: 27.99,
    icon: LampDesk,
  },
  {
    id: "30",
    name: "Mini PC Tower",
    supplier: "TechBuild",
    sku: "CPU-MINI-440",
    category: "Electronics",
    status: "Published",
    quantityInStock: 33,
    price: 499.99,
    icon: Cpu,
  },
];
